<a href="https://colab.research.google.com/github/Tugume/Machine-Learning-Project/blob/main/Machine_learning_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [13]:
#Creating arrays
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [3]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [4]:
np.full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [9]:

a=np.array([1,2,3,5,7,12])


In [15]:
a[2] = 10


In [17]:
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

In [19]:
np.linspace(0,100,11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

Multi-Dimentional Arrays

In [22]:
np.zeros((5, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [25]:
n= np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]

])

In [27]:
n[0,1] = 20
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [29]:
n[2] = [1,1,1,]

In [30]:
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 1,  1,  1]])

In [31]:
n[:, 1]

array([20,  5,  1])

Randomly generated arrays

In [32]:
np.random.rand(5,2)

array([[0.31251014, 0.03263097],
       [0.36540458, 0.93161611],
       [0.43290975, 0.16829575],
       [0.73849468, 0.48289563],
       [0.98424611, 0.65570134]])

In [33]:
np.random.seed(2)
np.random.rand(5,2)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [34]:
np.random.seed(2)
np.random.randn(5,2)

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [36]:
np.random.seed(2)
np.random.randint(low=0, high =100, size=(5,2))

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]])

In [35]:
np.random.seed(2)
100*np.random.rand(5,2)

array([[43.59949021,  2.59262318],
       [54.96624779, 43.53223926],
       [42.03678021, 33.0334821 ],
       [20.4648634 , 61.92709664],
       [29.96546737, 26.68272751]])

Element-wise operations

In [38]:
a =np.arange(5)
a

array([0, 1, 2, 3, 4])

In [39]:
a+1

array([1, 2, 3, 4, 5])

In [40]:
a*2

array([0, 2, 4, 6, 8])

In [42]:
10+(a*2)**2/100

array([10.  , 10.04, 10.16, 10.36, 10.64])

In [48]:
b=(10+(a*2))**2/100
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [49]:
a+b

array([1.  , 2.44, 3.96, 5.56, 7.24])

In [50]:
a/b

array([0.        , 0.69444444, 1.02040816, 1.171875  , 1.2345679 ])

Comparison Operations

In [52]:
a
a>=2

array([False, False,  True,  True,  True])

In [53]:
b
a>b

array([False, False,  True,  True,  True])

In [54]:
a[a>b]

array([2, 3, 4])

Summarizing Operations

In [55]:
a

array([0, 1, 2, 3, 4])

In [56]:
a.min()

np.int64(0)

In [57]:
a.sum()

np.int64(10)

In [58]:
a.std()

np.float64(1.4142135623730951)