<a href="https://colab.research.google.com/github/Tugume/Machine-Learning-Project/blob/main/Vector_Operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

u=np.array([2,4,5,6])

In [4]:
u

array([2, 4, 5, 6])

In [5]:
v =np.array([1,0,0,2])

In [6]:
v

array([1, 0, 0, 2])

In [7]:
u+v

array([3, 4, 5, 8])

Vector-vectir multiplication (dot Product)

In [29]:
u.shape[0]

3

In [27]:
def vector_vector_multiplication(u,v):
  assert u.shape[0] == v.shape[0]
  n=u.shape[0]
  result=0.0

  for i in range(n):
    result=result+u[i]*v[i]
  return result

In [21]:
vector_vector_multiplication(u,v)



array([ 11.,  32.,  45., 102.])

In [8]:
u=np.array([
    [2,4,5,6],
    [1,2,1,3],
    [3,2,2,1],

    ])

In [31]:
u

array([[2, 4, 5, 6],
       [1, 2, 1, 3],
       [3, 2, 2, 1]])

In [43]:
def matrix_vector_multiplication(u,v):
  assert u.shape[1]==v.shape[0]

  num_rows =u.shape[0]
  result=np.zeros(num_rows)

  for i in range(num_rows):
    result[i]=vector_vector_multiplication(u[i],v)
  return result

In [ ]:
matrix_vector_multiplication(u,v)

In [28]:
v=np.array([1, 0.5, 2, 1])

Matrix_Vector multiplication

In [34]:
v =np.array([

             [1,2,2],
             [0,0.5,1],
             [0,2,1],
             [2,1,0],

             ])

In [35]:
v

array([[1. , 2. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

Matrix-Matrix multiplication

In [40]:
def matrix_matrix_multiplication(u,v):
  assert u.shape[1] ==v.shape[0]
  num_row =u.shape[0]
  num_cols =v.shape[1]

  result=np.zeros((num_row,num_cols))

  for i in range(num_cols):
    vi=v[:,i]
    uvi=matrix_vector_multiplication(u,vi)
    result[:,i]=uvi
  return result

In [41]:
matrix_matrix_multiplication(u,v)

array([[14., 22., 13.],
       [ 7.,  8.,  5.],
       [ 5., 12., 10.]])

In [42]:
u.dot(v)

array([[14., 22., 13.],
       [ 7.,  8.,  5.],
       [ 5., 12., 10.]])

Identity Matrix

In [52]:
I= np.eye(3)

In [53]:
v

array([[1. , 2. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

In [54]:
v.dot(I)

array([[1. , 2. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

Inverse

In [57]:
Vs= v[[0,1,2]]
Vs

array([[1. , 2. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ]])

In [58]:
Vs_inv =np.linalg.inv(Vs)
Vs_inv

array([[ 1.        , -1.33333333, -0.66666667],
       [ 0.        , -0.66666667,  0.66666667],
       [ 0.        ,  1.33333333, -0.33333333]])

In [60]:
Vs_inv.dot(Vs)

array([[1.00000000e+00, 2.22044605e-16, 1.11022302e-16],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00]])